name: Continuous Integration with Jekyll and HTMLTEST

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - uses: actions/cache@v2
        with:
          path: tmp/.integration
          key: ${{ runner.os }}-integration

    - name: HTML Test
      run: |
        curl https://htmltest.wjdp.uk | bash
        bin/htmltest

    

    
